/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gt1loki;

public class App {
	public static int playerCount = 1;

    public static void main(String[] args) {
           
    		
		Client[] clients = new Client[playerCount];
		for(int index = 0; index < clients.length; index++) {
			clients[index] = new Client("127.0.0.1", index);
			clients[index].start();
		}

	}
}
